baseurl = "https://jskaza.github.io/my-foster-dogs"
metaDataFormat = "yaml"
title = "Safe With Us Dog Adoption Event"

[[menu.main]]
    name = "About"
    url = "about"
    weight = 1

[params]

    # Enable the darkmode toggle in header
    darkModeToggle = true
  
    # Enable search in header
    enableSearch = false

    # Custom copyright - optional
    copyright = "Copyright © 2022 - Safe With Us Animal Rescue · All rights reserved"
    favicon = "/fontawesome/paw.svg"

    # Color for the intro details and social links block, not applicable for dark mode
    # Supported values: Any color from TailwindCSS default colors
    # Reference: https://tailwindcss.com/docs/customizing-colors
        ascentColor = "#f8fafc"

    # The page bundle that is shown on the front page
    frontBundle = "dogs"

[params.homepage.social]
  instagram = "https://www.instagram.com/safewithusanimalrescue/?hl=en"
  facebook = "https://www.facebook.com/safewithusanimalrescue/"


[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true